using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LeagueSandbox.GameServer.Enums;

namespace LeagueSandbox.GameServer.NewGameObjects
{
    public class SpellData
    {
        public float SpellTotalTime { get; private set; }
        public float SpellCastTime { get; private set; }
        public int ClientData { get; private set; }
        public int AIData { get; private set; }
        public string VOEventCategory { get; private set; }
        public int SelectionPriority { get; private set; }
        public bool ManaUiOverride { get; private set; }
        public float Mana { get; private set; }
        public float FloatVarsDecimals { get; private set; }
        public float DeathRecapPriority { get; private set; }
        public string PointEffectName { get; private set; }
        public string AfterEffectName { get; private set; }
        public string HitEffectPlayerName { get; private set; }
        public string HitEffectName { get; private set; }
        public string HitBoneName { get; private set; }
        public int HitEffectOrientType { get; private set; }
        public int LookAtPolicy { get; private set; }
        public float LineDragLength { get; private set; }
        public float LineWidth { get; private set; }
        public float CircleMissileAngularVelocity { get; private set; }
        public float CircleMissileRadialVelocity { get; private set; }
        public bool MissilePerceptionBubbleRevealsStealth { get; private set; }
        public float MissilePerceptionBubbleRadius { get; private set; }
        public bool MissileBlockTriggersOnDestroy { get; private set; }
        public bool MissileUnblockable { get; private set; }
        public bool MissileClientExitFOWPrediction { get; private set; }
        public string TargetBoneName { get; private set; }
        public string MissileBoneName { get; private set; }
        public string MissileEffectEnemyName { get; private set; }
        public string MissileEffectPlayerName { get; private set; }
        public string MissileEffectName { get; private set; }
        public float MissileLifetime { get; private set; }
        public float MissileFixedTravelTime { get; private set; }
        public float MissileMinSpeed { get; private set; }
        public float MissileMaxSpeed { get; private set; }
        public float MissileAccel { get; private set; }
        public float MissileSpeed { get; private set; }
        public float PhysicalDamageRatio { get; private set; }
        public float SpellDamageRatio { get; private set; }
        public float CastFrame { get; private set; }
        public int CastType { get; private set; }
        public float LuaOnMissileUpdateDistanceInterval { get; private set; }
        public float LineMissileTimePulseBetweenCollisionSpellHits { get; private set; }
        public float LineMissileDelayDestroyAtEndSeconds { get; private set; }
        public float LineMissileTargetHeightAugment { get; private set; }
        public float MissileTargetHeightAugment { get; private set; }
        public float MissileGravity { get; private set; }
        public float BounceRadius { get; private set; }
        public float CastTargetAdditionalUnitsRadius { get; private set; }
        public float CastConeDistance { get; private set; }
        public float CastConeAngle { get; private set; }
        public float CastRadiusSecondary { get; private set; }
        public float CastRadius { get; private set; }
        public float CastRangeDisplayOverride { get; private set; }
        public float CastRange { get; private set; }
        public bool MinimapIconDisplayFlag { get; private set; }
        public bool ConsideredAsAutoAttack { get; private set; }
        public bool UpdateRotationWhenCasting { get; private set; }
        public bool HideRangeIndicatorWhenCasting { get; private set; }
        public bool IgnoreAnimContinueUntilCastFrame { get; private set; }
        public float UseAutoattackCastTime { get; private set; }
        public bool OrientRadiusTextureFromPlayer { get; private set; }
        public bool IgnoreRangeCheck { get; private set; }
        public bool NoWinddownIfCancelled { get; private set; }
        public bool DoNotNeedToFaceTarget { get; private set; }
        public bool MissileFollowsTerrainHeight { get; private set; }
        public bool LineMissileUsesAccelerationForBounce { get; private set; }
        public bool LineMissileBounces { get; private set; }
        public bool IsToggleSpell { get; private set; }
        public bool HavePointEffect { get; private set; }
        public bool HaveAfterEffect { get; private set; }
        public bool HaveHitBone { get; private set; }
        public bool HaveHitEffect { get; private set; }
        public bool UseAnimatorFramerate { get; private set; }
        public bool AlwaysSnapFacing { get; private set; }
        public bool ShowChannelBar { get; private set; }
        public bool DisableCastBar { get; private set; }
        public bool CanMoveWhileChanneling { get; private set; }
        public bool UseChargeTargeting { get; private set; }
        public bool UseChargeChanneling { get; private set; }
        public bool MinimapIconRotation { get; private set; }
        public bool CastRangeUseBoundingBoxes { get; private set; }
        public bool UseMinimapTargeting { get; private set; }
        public bool LineMissileTrackUnitsAndContinues { get; private set; }
        public bool LineMissileTrackUnits { get; private set; }
        public bool SpellRevealsChampion { get; private set; }
        public bool LineMissileEndsAtTargetPoint { get; private set; }
        public bool CursorChangesInTerrain { get; private set; }
        public bool CursorChangesInGrass { get; private set; }
        public bool CanOnlyCastWhileDead { get; private set; }
        public bool IsDisabledWhileDead { get; private set; }
        public bool BelongsToAvatar { get; private set; }
        public bool DoesntBreakChannels { get; private set; }
        public bool ApplyMaterialOnHitSound { get; private set; }
        public bool ApplyAttackEffect { get; private set; }
        public bool ApplyAttackDamage { get; private set; }
        public bool CantCastWhileRooted { get; private set; }
        public bool CantCancelWhileChanneling { get; private set; }
        public bool CantCancelWhileWindingUp { get; private set; }
        public bool CanOnlyCastWhileDisabled { get; private set; }
        public bool CanCastOrQueueWhileCasting { get; private set; }
        public bool CanCastWhileDisabled { get; private set; }
        public float CannotBeSuppressed { get; private set; }
        public bool CostAlwaysShownInUI { get; private set; }
        public float AmmoCountHiddenInUI { get; private set; }
        public float AmmoNotAffectedByCDR { get; private set; }
        public float AmmoRechargeTime { get; private set; }
        public int AmmoUsed { get; private set; }
        public int MaxAmmo { get; private set; }
        public float CancelChargeOnRecastTime { get; private set; }
        public float ChargeUpdateInterval { get; private set; }
        public float CastRangeGrowthDuration { get; private set; }
        public float CastRangeGrowthStartTime { get; private set; }
        public float CastRangeGrowthMax { get; private set; }
        public float StartCooldown { get; private set; }
        public float DelayTotalTimePercent { get; private set; }
        public float DelayCastOffsetPercent { get; private set; }
        public float CooldownTime { get; private set; }
        public float ChannelDuration { get; private set; }
        public float CastTime { get; private set; }
        public string SummonerSpellUpgradeDescription { get; private set; }
        public string KeywordWhenAcquired { get; private set; }
        public string MinimapIconName { get; private set; }
        public string ImgIconName { get; private set; }
        public string AnimationLeadOutName { get; private set; }
        public string AnimationWinddownName { get; private set; }
        public string AnimationLoopName { get; private set; }
        public string AnimationName { get; private set; }
        public int MaxHighlightTargets { get; private set; }
        public float Coefficient2 { get; private set; }
        public float Coefficient { get; private set; }
        public int EffectAmount { get; private set; }
        public string DynamicExtended { get; private set; }
        public string DynamicTooltip { get; private set; }
        public string SpellTags { get; private set; }
        public string Description { get; private set; }
        public string DisplayName { get; private set; }
        public string AlternateName { get; private set; }
        public int PlatformSpellInfo { get; private set; }
        public int ExcludedUnitTags { get; private set; }
        public int RequiredUnitTags { get; private set; }
        public int AffectsStatusFlags { get; private set; }
        public int AffectsTypeFlags { get; private set; }
        public int Flags { get; private set; }
        public float[] LocationTargettingWidthArray { get; private set; }
        public float[] LocationTargettingLengthArray { get; private set; }
        public int[] MaxAmmoArray { get; private set; }
        public float[] FloatVarsDecimalsArray { get; private set; }
        public float[] CooldownArray { get; private set; }
        public int[] AmmoUsedArray { get; private set; }
        public float[] AmmoRechargeTimeArray { get; private set; }
        public float[] CastRadiusSecondaryArray { get; private set; }
        public float[] CastRadiusArray { get; private set; }
        public float[] ChannelDurationArray { get; private set; }
        public float[] CastRangeGrowthMaxArray { get; private set; }
        public float[] CastRangeGrowthDurationArray { get; private set; }
        public float[] CastRangeDisplayOverrideArray { get; private set; }
        public float[] CastRangeArray { get; private set; }
        public float[] ManaCostArray { get; private set; }
        public string Name { get; private set; }
        public SpellDataTargetType TargettingType { get; private set; }
    }
}
